Allows @Param value in default contract to be taken from param names.
OpenFeign/feign pull request #1309
Opened 2020-11-12 20:51 UTC by krzyk

JEP 118 introduced javac option `-parameters` that adds to bytecode
method parameter names, so if code is compiled with that option
and @Param value is empty we can get that template parameter name
from method parameter name.

Fixes #1297.

2020-11-22 16:28 UTC, kdavisk6 requested changes
Simple enough.  Thank you for this.  If you could please update the `Readme` with this documentation?

2020-11-24 12:31 UTC, krzyk commented
@kdavisk6 I've updated the README.md

2020-11-24 17:23 UTC, kdavisk6 approved these changes

2020-12-02 08:23 UTC, krzyk commented
@kdavisk6 Can this be merged? Builds are passing and I would like to use it in my project

2020-12-21 16:40 UTC, merged