Fix bug for FeignException cannot get the correct charset (#1325)
OpenFeign/feign pull request #1345
Opened 2020-12-29 09:37 UTC by Linda-pan

Fix bug for FeignException cannot get the correct charset(#1325)

2020-12-29 14:47 UTC, kdavisk6 requested changes
@Linda-pan Please add a unit test for this use case.

2020-12-31 17:08 UTC, kdavisk6 commented
@Linda-pan Your latest changes are not formatted correctly, please fun `mvn install` locally to format the files, commit the changes and push the updates to fix the build

2021-01-18 03:20 UTC, Linda-pan reviewed
Fix bug for FeignException cannot get the correct charset and add some tests

2021-03-07 16:41 UTC, kdavisk6 approved these changes

2021-03-07 16:55 UTC, merged