feat: fix default retryer bug where initial wait period is the provid…
OpenFeign/feign pull request #1726
Opened 2022-08-15 14:39 UTC by FpMarinov

…ed period multiplied by 1.5, do a refactor on default retryer

2022-08-17 02:20 UTC, velo reviewed
Change makes sense, just needs to get build passing

2022-08-17 06:32 UTC, FpMarinov commented
> Change makes sense, just needs to get build passing

This seems to be the cause of the problem, the weird thing is the test passes fine locally:

[ERROR] loadBalancingTargetPath(feign.ribbon.LoadBalancingTargetTest)  Time elapsed: 0.825 s  <<< ERROR!
feign.RetryableException: Connection refused executing GET http://localhost:53935/context-path/servers

at feign.ribbon.LoadBalancingTargetTest.loadBalancingTargetPath(LoadBalancingTargetTest.java:83)

Caused by: java.net.ConnectException: Connection refused


Do you have any ideas what could be going wrong?

2022-10-09 16:02 UTC, kdavisk6 commented
Per #1727

2022-10-09 16:12 UTC, kdavisk6 requested changes
Changing how we count the number of attempts will break backward compatibility.  The original implementation is intentional.

2022-10-09 16:12 UTC, kdavisk6 commented on core/src/main/java/feign/Retryer.java
> +      if (attempt >= maxAttempts) {
This change is not backward compatible.  We count the attempt before sleeping intentionally.  This change will reduce the attempts by 1, please revert this change.

2022-10-09 16:12 UTC, kdavisk6 commented on core/src/main/java/feign/Retryer.java
> +          attempt++;
See my previous comment about counting attempts.

2022-10-09 16:12 UTC, kdavisk6 commented on core/src/main/java/feign/Retryer.java
> +      attempt++;
One more for the attempt count.

2022-10-09 16:12 UTC, kdavisk6 commented on ribbon/src/test/java/feign/ribbon/RibbonClientTest.java
> +      assertEquals("Hello", new Scanner(response.body().asInputStream()).nextLine());
There should be no need for a `Scanner` here.

2022-10-09 16:12 UTC, kdavisk6 commented on ribbon/src/test/java/feign/ribbon/RibbonClientTest.java
> +      assertEquals("Hello", new Scanner(response.body().asInputStream()).nextLine());
Also, this test is ignored.

2022-10-09 16:12 UTC, kdavisk6 commented on core/src/test/java/feign/RetryerTest.java
> +      Assert.assertEquals("Retry attempt not registered as expected", 1, retryer.attempt);
Last comment related to attempts.

2022-10-31 08:08 UTC, closed without merging