Add RemoteService to FeignContext
OpenFeign/feign pull request #2065
Opened 2023-05-26 16:33 UTC by wapkch

As mentioned in #2040, i think RemoteService should be set to FeignContext, so components like Skywalking could retrieve the host and port as the peer instead of using templated URL path.

@marcingrzejszczak Please review this draft PR.

2023-05-31 20:09 UTC, velo approved these changes

2023-06-01 06:53 UTC, marcingrzejszczak commented
Hey! How does it look like in Zipkin after your changes? Do you have a screenshot?

2023-06-01 09:08 UTC, wapkch commented
> Hey! How does it look like in Zipkin after your changes? Do you have a screenshot?

Sure, before the changes:
![711685610291_ pic](https://github.com/OpenFeign/feign/assets/32868606/8441299b-e5ca-4457-87d0-2aae0e70481a)

After the changes:
![701685610115_ pic](https://github.com/OpenFeign/feign/assets/32868606/e91d77d4-7790-4053-aad4-d80782545b88)

The FeignClient:
```java
@FeignClient(name = "jsonplaceholder", url = "jsonplaceholder.typicode.com")
public interface JsonPlaceholderFeignClient {

    @GetMapping("/posts")
    List<Post> loadPosts();

}

```

2023-06-01 13:05 UTC, wapkch commented
> What will happen if the other application (e.g. `jsonplaceholder`) is also instrumented and has a different name (e.g. `foo`)? The standard practice is that the service name gets automatically resolved as the server's local service name. Can you test this against an app (e.g. a Spring Boot 3 app) that has an MVC filter that is instrumented and show the screenshot?

It will be like this:
![image](https://github.com/OpenFeign/feign/assets/32868606/4a1e94de-0ec1-4433-9902-1e14126c170e)
In this test, `jsonplaceholder` application's `spring.application.name` is `foo`, and the FeignClient's name is still `jsonplaceholder`

2023-06-01 14:04 UTC, marcingrzejszczak commented
So this is with the changes from this PR? Cause the second span still has `application` there as a service name?

2023-06-02 01:12 UTC, wapkch commented
> So this is with the changes from this PR? Cause the second span still has `application` there as a service name?

Yes, i confirmed, the second span just had a different service name compared with the case that the remote service did not report traces.

2023-06-05 08:05 UTC, marcingrzejszczak commented
I'm asking cause this works well if you're not using apache skywalking. WDYT about doing the setting of remote service name and address inside skywalking via the observation convention mechanism? Or the observation filter?

2023-06-10 16:04 UTC, wapkch commented
> I'm asking cause this works well if you're not using apache skywalking. WDYT about doing the setting of remote service name and address inside skywalking via the observation convention mechanism? Or the observation filter?

I considered this option, but i think the problem of doing the setting inside skywalking is that skywalking have to distinguish the different Sender implementations(Retrieve the remote service name and address from carrier then set to SenderContext), there are so many SenderContext and carrier implementations, it will be hard to maintain in skywalking. So i think doing the settings in seperated projects will be better.

2023-06-12 13:07 UTC, marcingrzejszczak commented
>  there are so many SenderContext and carrier implementations(e.g., Feign, Resttemplate, messaging...)

So you're saying that there will be the same problem with all of these implementations? I'm just curious if this is not a problem related to Skywalking as such. I don't recall having such problems with Zipkin / Tempo etc.

2023-06-19 21:06 UTC, velo requested changes
When ready, please move from draft

2023-06-19 21:06 UTC, velo commented on micrometer/src/main/java/feign/micrometer/FeignContext.java
> +        setRemoteServiceAddress(url.getProtocol() + "://" + url.getHost() + ":" + url.getPort());
Wouldn't `setRemoteServiceAddress(url.toString())` do the trick?

2023-06-19 21:06 UTC, velo commented on micrometer/src/main/java/feign/micrometer/FeignContext.java
> +    } catch (Exception ignored) {
what exception is been ignored here?

probably should re-throw it, as will be impossible for people to understand why something is not working if we are eating the exception

2023-08-29 05:06 UTC, velo commented
No answer to feedback and still on draft, will close, if needed please reopen

2023-08-29 05:06 UTC, closed without merging