Fixed feign-micrometer exception handling.
OpenFeign/feign pull request #2644
Opened 2024-11-10 18:54 UTC by r-dimitrov

The current MR improves exception handling for **feign-micrometer** clients. Previously, exceptions such as **404**, **400**, **500**, etc., were not marked with error=true in the Observation and thus were not reported in the trace as errors.

The exception declaration has been changed from (**FeignException ex**) to (**Exception ex**), as none of the supported clients (e.g., Apache HttpClient, OkHttp) throws FeignException, but rather client-specific exceptions.

The fix is currently in production in my organization, and it has been working effectively.

Fixes #2566

2024-11-22 12:57 UTC, r-dimitrov commented
I've just added some fixes, as there were exceptions when some clients had defined a custom ErrorDecoder. The input stream is consumed, and the decoder throws an exception. This way, we are copying the input stream so it can be used multiple times.

2025-01-04 14:41 UTC, kdavisk6 requested changes
Can we discuss the need to read the request body into memory more?

2025-01-04 14:41 UTC, kdavisk6 commented on micrometer/src/main/java/feign/micrometer/MicrometerObservationCapability.java
> +        }
If your intent is to properly flag the request with the appropriate error based on status, reading the response into memory _before_ checking the status code may be problematic in certain scenarios.  Particularly in one where a large number of successful responses are monitored with large data sets.  

By doing this, we impress upon our users that their applications must be able to stream all data from all tracked operations into memory in order to observe this.  

Can you help me understand the exceptions observed when trying to observe a client with a custom `ErrorDecoder`?

If this must be part of the solution, we should document this assumption and control this behavior with a configurable feature flag, initially off, and allow our users to make the decision whether to take this on.

2025-01-20 08:36 UTC, r-dimitrov commented on micrometer/src/main/java/feign/micrometer/MicrometerObservationCapability.java
> +        }
Hey, @kdavisk6 , thank you for your comment. I've made the changes to cache exceptions (errors) only, so successful responses are no longer cached.

Regarding the custom `ErrorDecoder`, the issue is that when the exception response message body is read, the stream is consumed in `MicrometerObservationCapability.java`, making it unavailable in the `ErrorDecoder`. This is problematic because, in most cases, we need to read the response again and map it to another object. When the response is cached, we can read the response as many times as needed. For example, this is useful if we have loggers, additional logic in filters, and so on.

To summarize:
We need to read the response body for exceptions (client/server error codes in the response) to mark the span with error details and exception information. If we don't cache the response, we cannot read it in another layer, such as the `ErrorDecoder`, because it is already consumed for observability purposes.

2025-01-20 18:48 UTC, kdavisk6 commented on micrometer/src/main/java/feign/micrometer/MicrometerObservationCapability.java
> +        }
Thanks for the clarification.  

Reviewing `MicrometerObservabilityCapability`, I'm do not see it explicitly consuming the `Response.body`, only wrapping it.  Do you have an example where the `Response` is consumed during metrics processing?  I'd like to confirm that this is intentional or not.  If not, then we should address that, which should remove the need for this workaround.

If it is intentional, I'm still leery of allowing this without some level of user control.  I would like to see some way for users to control this behavior.  There may be situations where even the error response may be large enough to cause memory pressure and we should not be pressing this onto our users without their consent.  

One way is for us to check the `Content-Length` on the response and if that is over a certain threshold, we should defer streaming the response into memory.  Another is to have a configurable option as part of the `MicrometerCapability` that  explicitly enables response caching.

2025-01-28 14:03 UTC, r-dimitrov commented on micrometer/src/main/java/feign/micrometer/MicrometerObservationCapability.java
> +        }
Hello, @kdavisk6,
The `response` is not explicitly consumed but is necessary for tracking the exact exception returned from the given HTTP call. To mark the span as an exception, a `Throwable` object is required, which is subsequently used here:
[https://github.com/micrometer-metrics/tracing/blob/e64b9195d0aec18c74353e274d9fef05022061f4/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpan.java#L171](https://github.com/micrometer-metrics/tracing/blob/e64b9195d0aec18c74353e274d9fef05022061f4/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpan.java#L171)
As you can see getMessage() is invoked for printing the details about the exception.
Without consuming and mapping the response to an Exception (Throwable), it is not possible to capture the core root cause of the exception. The image below shows the desired behaviour.

<img width="1728" alt="Screenshot 2025-01-28 at 15 57 34" src="https://github.com/user-attachments/assets/12b031a5-b6eb-42b7-9036-1c707befd879" />

2025-02-11 12:04 UTC, velo commented
Ops, closed by mistake, my bad

2025-04-15 07:18 UTC, r-dimitrov commented
@velo @kdavisk6 Hello, guys! Could we proceed with merging the PR? It's in good shape, and it's truly a must-have feature when it comes to distributed tracing. Thank you so much for all the great work you do — it's truly appreciated!

2025-04-22 10:32 UTC, velo approved these changes

2025-05-28 20:57 UTC, closed without merging